ReleasePR
rusakoz/WebLab4-3s pull request #9
Opened 2024-01-21 19:29 UTC by rusakoz

2024-01-22 09:52 UTC, danilkladnitsky requested changes

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/java/org/lab4/wed/weblab4/controller/ResultsRestController.java
> +            return new ResponseEntity<>("{\"error\":\""+ "Записи не найдены" +"\"}", HttpStatus.OK);
Не очень хорошо вручную формировать json. Либо создайте отдельный класс для формирования таких сообщений, либо так:

```
Map<String, String> message = new HashMap<>();
message.put("error", "Записи не найдены");
return new ResponseEntity<>(message, HttpStatus.OK);
```

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/java/org/lab4/wed/weblab4/db/entity/Results.java
> +@Table(name = "results", schema = "s338963")
Схему было бы неплохо куда-нибудь в секрет сохранить

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/App.vue
> +</style>
Лишний тег

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/assets/style.css
> +html{
По хорошему бы не хранить все стили в одном файле, а сохранять рядом с соответствующими компонентами

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/components/Login.vue
> +  })
Саму ошибку авторизации было бы славно также демонстрировать

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/components/Login.vue
> +    const resJson = response.json()
Сразу конвертируйте в json с помощью await, а потом забирайте свойство error
```suggestion
    const resJson = await response.json()
```

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/components/Login.vue
> +    if (typeof errorText !== 'undefined') {
```
const hasError = Boolean(error)

if(hasError) {
...
}
```

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/components/Registration.vue
> +}
Можно исправить как в прошлых комментариях
А лучше вынести в отдельные функции и переиспользовать

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/components/mainContents/Graph.vue
> +        })
```suggestion
        return useFetchPostJwt('/result/save', {
            x,
            y,
            r,
        })
```

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/components/mainContents/Graph.vue
> +    if (response.status === 201) {
```
const ENTITY_CREATED_CODE = 201
const FORBIDDEN_CODE = 403
...

const { status, error } = response;

if(status=== ENTITY_CREATED_CODE) {
...
} 
```

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/components/mainContents/Graph.vue
> +            tableData.data.push({
const { x, y, r, date }  = data;

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/use/graph/loadTable.js
> +    }
https://gomakethings.com/the-early-return-pattern-in-javascript/
https://habr.com/ru/articles/348074/
https://github.com/bespoyasov/refactor-like-a-superhero/blob/main/manuscript-ru/12-error-handling.md
![image](https://github.com/rusakoz/WebLab4-3s/assets/82809125/37ffa2c6-ee4c-4873-a5ab-937dff45ab85)

2024-01-22 09:52 UTC, danilkladnitsky commented on src/main/resources/js/use/requests/fetchPostJwt.js
> +        'Authorization': 'Bearer ' + localStorage.getItem('userAccessToken')
Токен лучше передавать в аргументах функции

2024-01-23 01:45 UTC, rusakoz commented on src/main/java/org/lab4/wed/weblab4/db/entity/Results.java
> +@Table(name = "results", schema = "s338963")
Сделал схему дефолтной для всего проекта в yml конфиге. Но если нужно будет использовать несколько схем, то без понятия что делать в этом случае, так как аннотация требует статических данных и напрямую переменную окружения не передать.

2024-01-23 18:48 UTC, danilkladnitsky approved these changes
8.5

2024-08-04 19:58 UTC, merged